export const COUPON_DETAILS_REQUEST = "COUPON_DETAILS_REQUEST";
export const COUPON_DETAILS_SUCCESS = "COUPON_DETAILS_SUCCESS";
export const COUPON_DETAILS_FAIL = "COUPON_DETAILS_FAIL";
export const COUPON_DETAILS_EXPIRED = "COUPON_DETAILS_EXPIRED";
export const COUPON_DETAILS_DISABLED = "COUPON_DETAILS_DISABLED"